#!/usr/bin/env bash

set -u

if [[ ${GPUI_WASM_TEST_SHELL:-0} != 1 ]]; then
	develop=(nix develop --ignore-environment --keep HOME)
	if [[ -n ${TMPDIR:-} ]]; then
		develop+=(--keep TMPDIR)
	fi
	exec "${develop[@]}" -c env GPUI_WASM_TEST_SHELL=1 "$0" "$@"
fi

failures=0

run_check() {
	"$@"
	status=$?
	if (( status != 0 )); then
		failures=$((failures + 1))
	fi
}

run_check ./tests/cli/development_dependencies
run_check ./tests/cli/repository_boundary
run_check ./tests/cli/launcher_cwd
run_check ./tests/cli/web_startup_surface
run_check cargo test --no-default-features --features native-runtime
run_check cargo test --no-default-features --features portable-runtime
run_check cargo test --lib --no-default-features --features web web::tests
run_check nix develop .#web --ignore-environment --keep HOME --keep TMPDIR -c \
	cargo --config web/cargo-config.toml build --lib --target wasm32-unknown-unknown --no-default-features --features portable-runtime
run_check nix develop .#web --ignore-environment --keep HOME --keep TMPDIR -c \
	cargo --config web/cargo-config.toml build --bin aedicule-web --target wasm32-unknown-unknown --no-default-features --features web
run_check ./tests/cli/web_delivery
run_check cargo test --bin gpui-wasm
run_check cargo test --test gui_cli
run_check cargo check
run_check ./tests/cli/build_partition

if (( failures > 255 )); then
	exit 255
fi
exit "$failures"
