[target.wasm32-unknown-unknown]
# A wasm module cannot be executed as a native binary, so the test harness needs
# a host to load it.
runner = "wasm-bindgen-test-runner"
rustflags = [
	"-C", "target-feature=+bulk-memory,+mutable-globals",
	"-C", "link-arg=--export=__heap_base",
]

[unstable]
build-std = ["std", "panic_abort"]
