[target.wasm32-unknown-unknown]
# A wasm module cannot be executed as a native binary, so the test harness needs
# a host to load it.
runner = "wasm-bindgen-test-runner"
rustflags = [
	"-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
	"-C", "link-arg=--shared-memory",
	"-C", "link-arg=--max-memory=268435456",
	"-C", "link-arg=--import-memory",
	"-C", "link-arg=--export=__heap_base",
	"-C", "link-arg=--export=__wasm_init_tls",
	"-C", "link-arg=--export=__tls_size",
	"-C", "link-arg=--export=__tls_align",
	"-C", "link-arg=--export=__tls_base",
]

[unstable]
build-std = ["std", "panic_abort"]
